### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/coconut-pytorch#1]
- [ ] handle bot / eot
- [ ] handle losses
- [ ] checkpointing
- [ ] allow for multiple thought tokens per step
- [ ] allow for multi-streams + merging
